export const GET_BEER_LIST_REQUEST = 'GET_BEER_LIST_REQUEST';
export const GET_BEER_LIST_SUCCESS = 'GET_BEER_LIST_SUCCESS';
export const GET_BEER_LIST_FAILURE = 'GET_BEER_LIST_FAILURE';
export const SELECT_BEER_IN_TABLE = 'SELECT_BEER_IN_TABLE';
export const SWITCH_TABLE_COLUMNS = 'SWITCH_TABLE_COLUMNS';